
package soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloSoap", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testService", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/", className = "soap.ws.TestService")
    @ResponseWrapper(localName = "testServiceResponse", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/", className = "soap.ws.TestServiceResponse")
    public String testService();

    /**
     * 
     * @return
     *     returns soap.ws.Goods
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGoods", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/", className = "soap.ws.GetGoods")
    @ResponseWrapper(localName = "getGoodsResponse", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/", className = "soap.ws.GetGoodsResponse")
    public Goods getGoods();

    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloTo", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/", className = "soap.ws.SayHelloTo")
    @ResponseWrapper(localName = "sayHelloToResponse", targetNamespace = "http://ws.soap.study.bondarenko.nixsolutions.com/", className = "soap.ws.SayHelloToResponse")
    public String sayHelloTo(
        @WebParam(name = "text", targetNamespace = "")
        String text);

}
